import assert from 'node:assert/strict';
import test from 'node:test';
import { Buffer } from 'node:buffer';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { clampElevenLabsDynamicVariables } from '@/lib/ai/clampElevenLabsDynamicVariables';
import { extractTextFromResumeBuffer } from './extractTextFromResumeBuffer';
import { isUnsafeResumePlainText, sanitizeResumePlainText } from './extractionQuality';

const require = createRequire(import.meta.url);

function validPdfResume(): Buffer {
  // Deterministic, uncompressed PDF 1.3 fixture generated by ReportLab. Keeping
  // the known-good bytes avoids OS-specific output from runtime PDF generators.
  return Buffer.from(
    'JVBERi0xLjMKJZOMi54gUmVwb3J0TGFiIEdlbmVyYXRlZCBQREYgZG9jdW1lbnQgKG9wZW5zb3VyY2UpCjEgMCBvYmoKPDwKL0YxIDIgMCBSCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9CYXNlRm9udCAvSGVsdmV0aWNhIC9FbmNvZGluZyAvV2luQW5zaUVuY29kaW5nIC9OYW1lIC9GMSAvU3VidHlwZSAvVHlwZTEgL1R5cGUgL0ZvbnQKPj4KZW5kb2JqCjMgMCBvYmoKPDwKL0NvbnRlbnRzIDcgMCBSIC9NZWRpYUJveCBbIDAgMCA2MTIgNzkyIF0gL1BhcmVudCA2IDAgUiAvUmVzb3VyY2VzIDw8Ci9Gb250IDEgMCBSIC9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSSBdCj4+IC9Sb3RhdGUgMCAvVHJhbnMgPDwKCj4+IAogIC9UeXBlIC9QYWdlCj4+CmVuZG9iago0IDAgb2JqCjw8Ci9QYWdlTW9kZSAvVXNlTm9uZSAvUGFnZXMgNiAwIFIgL1R5cGUgL0NhdGFsb2cKPj4KZW5kb2JqCjUgMCBvYmoKPDwKL0F1dGhvciAoYW5vbnltb3VzKSAvQ3JlYXRpb25EYXRlIChEOjIwMDAwMTAxMDAwMDAwKzAwJzAwJykgL0NyZWF0b3IgKGFub255bW91cykgL0tleXdvcmRzICgpIC9Nb2REYXRlIChEOjIwMDAwMTAxMDAwMDAwKzAwJzAwJykgL1Byb2R1Y2VyIChSZXBvcnRMYWIgUERGIExpYnJhcnkgLSBcKG9wZW5zb3VyY2VcKSkgCiAgL1N1YmplY3QgKHVuc3BlY2lmaWVkKSAvVGl0bGUgKHVudGl0bGVkKSAvVHJhcHBlZCAvRmFsc2UKPj4KZW5kb2JqCjYgMCBvYmoKPDwKL0NvdW50IDEgL0tpZHMgWyAzIDAgUiBdIC9UeXBlIC9QYWdlcwo+PgplbmRvYmoKNyAwIG9iago8PAovTGVuZ3RoIDIzMQo+PgpzdHJlYW0KMSAwIDAgMSAwIDAgY20gIEJUIC9GMSAxMiBUZiAxNC40IFRMIEVUCkJUIC9GMSAxOCBUZiAyMS42IFRMIEVUCkJUIDEgMCAwIDEgNDggNzMwIFRtIChKYW5lIERvZSBSZXN1bWUpIFRqIFQqIEVUCkJUIC9GMSAxMSBUZiAxMy4yIFRMIEVUCkJUIDEgMCAwIDEgNDggNjk1IFRtIChFeHBlcmllbmNlOiBEYXRhYmFzZSBhZG1pbmlzdHJhdG9yIHVzaW5nIFNRTCBhbmQgUG9zdGdyZVNRTC4pIFRqIFQqIEVUCiAKZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgOAowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwNjEgMDAwMDAgbiAKMDAwMDAwMDA5MiAwMDAwMCBuIAowMDAwMDAwMTk5IDAwMDAwIG4gCjAwMDAwMDAzOTIgMDAwMDAgbiAKMDAwMDAwMDQ2MCAwMDAwMCBuIAowMDAwMDAwNzIxIDAwMDAwIG4gCjAwMDAwMDA3ODAgMDAwMDAgbiAKdHJhaWxlcgo8PAovSUQgCls8MWMxNzgxOThmYmRmYTUxYjI1OTk1ZDg5ZDQxMDIwNDM+PDFjMTc4MTk4ZmJkZmE1MWIyNTk5NWQ4OWQ0MTAyMDQzPl0KJSBSZXBvcnRMYWIgZ2VuZXJhdGVkIFBERiBkb2N1bWVudCAtLSBkaWdlc3QgKG9wZW5zb3VyY2UpCgovSW5mbyA1IDAgUgovUm9vdCA0IDAgUgovU2l6ZSA4Cj4+CnN0YXJ0eHJlZgoxMDYxCiUlRU9GCg==',
    'base64',
  );
}

async function mammothDocxFixture(): Promise<Buffer> {
  const packagePath = require.resolve('mammoth/package.json');
  return readFile(join(dirname(packagePath), 'test', 'test-data', 'single-paragraph.docx'));
}

test('extractTextFromResumeBuffer: UTF-8 .txt', async () => {
  const buf = Buffer.from('Hello résumé\nline two', 'utf-8');
  const t = await extractTextFromResumeBuffer(buf, 'txt');
  assert.match(t, /résumé/);
});

test('extractTextFromResumeBuffer: extracts a real text PDF', async () => {
  const text = await extractTextFromResumeBuffer(validPdfResume(), 'pdf');
  assert.match(text, /Jane Doe Resume/);
  assert.match(text, /Database administrator/);
});

test('extractTextFromResumeBuffer: extracts a real DOCX', async () => {
  const text = await extractTextFromResumeBuffer(await mammothDocxFixture(), '.docx');
  assert.equal(text, 'Walking on imported air');
});

test('extractTextFromResumeBuffer: malformed PDF never becomes resume text', async () => {
  const rawPdf = [
    '%PDF-1.7',
    '1 0 obj',
    '<< /Type /Catalog >>',
    'stream',
    'profile={{member_full_name}}',
    'endstream',
    'endobj',
    '%%EOF',
  ].join('\n');

  await assert.rejects(() => extractTextFromResumeBuffer(Buffer.from(rawPdf), 'pdf'));
});

test('extractTextFromResumeBuffer: malformed DOCX never becomes resume text', async () => {
  const rawDocx = Buffer.from(
    'PK\u0003\u0004 [Content_Types].xml word/document.xml {{resume_text}} not really a zip',
    'utf-8',
  );
  await assert.rejects(() => extractTextFromResumeBuffer(rawDocx, 'docx'));
});

test('extractTextFromResumeBuffer: invalid UTF-8 and binary masquerading as TXT fail closed', async () => {
  await assert.rejects(() => extractTextFromResumeBuffer(Buffer.from([0xff, 0xfe, 0xfd]), 'txt'));
  await assert.rejects(() =>
    extractTextFromResumeBuffer(Buffer.from('%PDF-1.7\n1 0 obj\nstream\nbytes\nendstream\nendobj'), 'txt'),
  );
});

test('resume text safety guard rejects containers, parser output, and agent placeholders', () => {
  const parserDiagnostic = [
    'Error: Invalid PDF structure',
    'at Object.parse (webpack:///src/pdf.js:24:23)',
  ].join('\n');
  const zipContainer = 'PK [Content_Types].xml word/document.xml';

  assert.equal(isUnsafeResumePlainText('%PDF-1.7\n1 0 obj\nendobj\n%%EOF'), true);
  assert.equal(isUnsafeResumePlainText(parserDiagnostic), true);
  assert.equal(isUnsafeResumePlainText(zipContainer), true);
  assert.equal(sanitizeResumePlainText('Candidate: {{member_full_name}}\nExperience'), '');
  assert.equal(
    sanitizeResumePlainText('Jane Doe\r\nExperience\r\nStreamlined PDF workflows for staff.'),
    'Jane Doe\nExperience\nStreamlined PDF workflows for staff.',
  );
});

test('ElevenLabs boundary drops poisoned resume variables and reconciles has_resume', () => {
  const poisoned = '%PDF-1.7\n1 0 obj\nstream\n{{member_full_name}}\nendstream\nendobj\n%%EOF';
  const guarded = clampElevenLabsDynamicVariables({
    member_first_name: 'Jane',
    resume_text: poisoned,
    live_resume_draft: poisoned,
    has_resume: true,
  });

  assert.equal(guarded.member_first_name, 'Jane');
  assert.equal(guarded.resume_text, '');
  assert.equal(guarded.live_resume_draft, '');
  assert.equal(guarded.has_resume, 'false');

  const validResume = 'Jane Doe\nExperience\nDatabase administrator using SQL and PostgreSQL.';
  const valid = clampElevenLabsDynamicVariables({ resume_text: validResume, has_resume: true });
  assert.equal(valid.resume_text, validResume);
  assert.equal(valid.has_resume, 'true');
});

test('plain-text save route rejects poisoned resume data before storage', async () => {
  const route = await readFile(
    join(process.cwd(), 'app', 'api', 'member', 'resume', 'plain-text', 'route.ts'),
    'utf-8',
  );
  const sanitizeIndex = route.indexOf('sanitizeResumePlainText(raw)');
  const rejectionIndex = route.indexOf('if (raw.trim() && !safeText)');
  const uploadIndex = route.indexOf('.upload(path, plainText');

  assert.ok(sanitizeIndex >= 0);
  assert.ok(rejectionIndex > sanitizeIndex);
  assert.ok(uploadIndex > rejectionIndex);
});
