/**
 * Live Coursera catalog mapping discovered from the Workforce Advancement Project
 * Coursera For Business API on 2026-04-23.
 *
 * Purpose: keep WAP course names/slugs aligned with the real Coursera learning
 * paths so xAPI/webhook completions and deep links resolve accurately.
 */

export type DiscoveredCourseraCourse = {
  courseId: string;
  slug: string;
  name: string;
  partner: string | null;
  estimatedHours: number;
};

export type DiscoveredCourseraProgram = {
  workforceProgramSlug: string;
  courseraProgramId: string;
  courseraProgramName: string;
  courseraCollectionId: string;
  courseraCollectionTitle: string;
  publicProgramUrl: string;
  courseCount: number;
  courses: DiscoveredCourseraCourse[];
};

export const DISCOVERED_COURSERA_PROGRAMS: Record<string, DiscoveredCourseraProgram> = {
  "comptia-a-professional-certificate": {
    workforceProgramSlug: "comptia-a-professional-certificate",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "JpPZG",
    courseraCollectionTitle: "CompTIA A+ Professional Certificate",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 10,
    courses: [
      {
        courseId: "7sBiclFIEeetjQ5ppGVTyA",
        slug: "technical-support-fundamentals",
        name: "Technical Support Fundamentals",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "ySI6pmchEe--dw7PPVphLw",
        slug: "packt-it-fundamentals-and-hardware-essentials-yqged",
        name: "IT Fundamentals and Hardware Essentials",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "DRKQhcn7EfCGDQr_wTYZuQ",
        slug: "packt-foundations-of-it-and-core-hardware-components-gavrv",
        name: "Foundations of IT and Core Hardware Components",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "J6uAMWcgEe-ZVAr_5CUYPw",
        slug: "packt-foundations-of-computer-hardware-and-storage-fneta",
        name: "Foundations of Computer Hardware and Storage",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "RP5nqGeBEe-ZVAr_5CUYPw",
        slug: "packt-operating-systems-and-networking-fundamentals-bokjh",
        name: "Operating Systems and Networking Fundamentals",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "S3G1qWbiEe-EPwr_9XyAcQ",
        slug: "packt-networking-peripherals-and-wireless-technologies-fhkx1",
        name: "Networking, Peripherals, and Wireless Technologies",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "XnYYsmbgEe-WbhKfqhh3sw",
        slug: "packt-advanced-networking-security-and-it-operations-fgrrb",
        name: "Advanced Networking, Security, and IT Operations",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "pG5HkGelEe--dw7PPVphLw",
        slug: "packt-advanced-networking-virtualization-and-it-security-pzolo",
        name: "Advanced Networking, Virtualization, and IT Security",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "uOyjBdflEeqckg5GnG0pSw",
        slug: "comptia-practice",
        name: "CompTIA Practice",
        partner: "LearnQuest",
        estimatedHours: 10,
      },
      {
        courseId: "bbLUnmLQEe66xBLRCmM3Cw",
        slug: "practice-exam-for-comptia-a",
        name: "Practice Exams for CompTIA A+ Certification: Core 1 & Core 2",
        partner: "IBM",
        estimatedHours: 10,
      },
    ],
  },
  "project-management-professional-certificate-microsoft": {
    workforceProgramSlug: "project-management-professional-certificate-microsoft",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "1cvGr",
    courseraCollectionTitle: "Project Management Professional Certificate (Microsoft)",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 10,
    courses: [
      {
        courseId: "lgy789C8Ee6SjxKHxThXWw",
        slug: "project-management-fundamentals-microsoft",
        name: "Project Management Fundamentals",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "ETzWTdC9Ee6SjxKHxThXWw",
        slug: "team-building-and-leadership-in-project-management",
        name: "Team Building and Leadership in Project Management",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "YbrDRtC9Ee6SjxKHxThXWw",
        slug: "project-manager-engagement-with-stakeholders",
        name: "Project Manager Engagement with Stakeholders",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "KQ6GstDAEe6P2wphYfoNOQ",
        slug: "process-groups-and-processes-in-project-management",
        name: "Process Groups and Processes in Project Management",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "vuAsldC-Ee6P2wphYfoNOQ",
        slug: "project-management-principles",
        name: "Project Management Principles",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "u3rsKNC_Ee6SjxKHxThXWw",
        slug: "project-management-performance-domains",
        name: "Project Management Performance Domains",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "MLjf49C-Ee6SjxKHxThXWw",
        slug: "pmp-formulas",
        name: "PMP Formulas",
        partner: "Microsoft",
        estimatedHours: 10,
      },
      {
        courseId: "ocXG5O4OEe6cohJOlykk1Q",
        slug: "pm4r-agile-5-steps-for-hybrid-management-of-projects",
        name: "PM4R Agile: 5 steps for hybrid management of projects",
        partner: "Banco Interamericano de Desarrollo",
        estimatedHours: 10,
      },
      {
        courseId: "NGstiiJNEe-qLxJFbw2Hbw",
        slug: "pm4r-agile-mindset-in-development-projects",
        name: "PM4R Agile: Agile Mindset in Development Projects",
        partner: "Banco Interamericano de Desarrollo",
        estimatedHours: 10,
      },
      {
        courseId: "ByqSENDBEe6SjxKHxThXWw",
        slug: "pmp-application-process-and-practice-exam",
        name: "PMP Application Process and Practice Exam",
        partner: "Microsoft",
        estimatedHours: 10,
      },
    ],
  },
  "it-support-professional-certificate-ibm": {
    workforceProgramSlug: "it-support-professional-certificate-ibm",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "0lodU",
    courseraCollectionTitle: "IT Support Professional Certificate (IBM)",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 9,
    courses: [
      {
        courseId: "rNyuLa-pEeytqw64hz8ZCw",
        slug: "introduction-to-technical-support",
        name: "Introduction to Technical Support",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "wtYRSE1kEeyLIRLL9niz0w",
        slug: "introduction-to-hardware-and-operating-systems",
        name: "Introduction to Hardware and Operating Systems",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "mFu9FE1kEeyLIRLL9niz0w",
        slug: "introduction-software-programming-and-databases",
        name: "Introduction to Software, Programming, and Databases",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "P0ciGZT0EeyHuA5cIqn4NQ",
        slug: "introduction-to-networking-and-storage",
        name: "Introduction to Networking and Storage",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "P6EH-AfjEeqBYw5XkWz7vw",
        slug: "introduction-to-cloud",
        name: "Introduction to Cloud Computing",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "YlfzdXJKEeyKjA79ESMRTQ",
        slug: "introduction-to-cybersecurity-essentials",
        name: "Introduction to Cybersecurity Essentials",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "873t-sJ3EeyZlw5yhMZTYQ",
        slug: "technical-support-case-studies",
        name: "Technical Support (IT) Case Studies and Capstone",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "tYQTkiDCEe6zFgoHXpnxeQ",
        slug: "practice-exam-for-comptia-itf-plus-certification",
        name: "Practice Exam for CompTIA Tech+ Certification",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "R56tWWBoEe2TzA7_9n9MNw",
        slug: "tech-support-career-guide-and-interview-preparation",
        name: "Tech Support Career Guide and Interview Preparation",
        partner: "IBM",
        estimatedHours: 10,
      },
    ],
  },
  "health-information-technology-mchit": {
    workforceProgramSlug: "health-information-technology-mchit",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "CRbEJ",
    courseraCollectionTitle: "Medical Coding, Billing, and Heath Information Technician Certificate (MBCHIT)",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 15,
    courses: [
      {
        courseId: "NRbkx_ZREe2OqwqhrYNGhQ",
        slug: "medical-terminology-anatomy-physiology-fundamentals",
        name: "Medical Terminology, Anatomy, and Physiology Fundamentals",
        partner: "MedCerts",
        estimatedHours: 10,
      },
      {
        courseId: "kyfEm7DIEfCsnQ73ldDVQw",
        slug: "register-patients--validate-data",
        name: "Register Patients & Validate Data",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "jb0fG5ClEe-KjBKlSS1PLQ",
        slug: "revenue-cycle-billing-and-coding",
        name: "Revenue Cycle, Billing, and Coding",
        partner: "Johns Hopkins University",
        estimatedHours: 10,
      },
      {
        courseId: "4vJ2DufMEe-ccQr_xjRSew",
        slug: "the-billing-and-collection-process",
        name: "The Billing and Collection Process",
        partner: "AAPC",
        estimatedHours: 10,
      },
      {
        courseId: "ORD0I55eEe2a0hItqNBhjQ",
        slug: "medical-billing-coding-essentials",
        name: "Medical Billing and Coding Essentials",
        partner: "MedCerts",
        estimatedHours: 10,
      },
      {
        courseId: "kYlX_qm0EfCZ0RJy-KWDlw",
        slug: "medical-billing-code-claim-collect",
        name: "Medical Billing: Code, Claim, Collect",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "6JQCyKqNEfCK2RJYz7KGmw",
        slug: "medical-billing-code-and-claim-cleanly",
        name: "Medical Billing: Code and Claim Cleanly",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "6y4eyrMCEfCVOAr_-ssqDQ",
        slug: "medical-coding-for-max-reimbursement",
        name: "Medical Coding for Max Reimbursement",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "Se-fZQWhEfG28A6LLakGFQ",
        slug: "reconciliation-billing-and-collections-optimization",
        name: "Reconciliation, Billing, and Collections Optimization",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "q5bxtK88EfCvhhJvy8XwzQ",
        slug: "medical-records-protect-patient-privacy",
        name: "Medical Records: Protect Patient Privacy",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "dj1_WJClEe-jlw4NkAElrw",
        slug: "data-and-electronic-health-records",
        name: "Data and Electronic Health Records",
        partner: "Johns Hopkins University",
        estimatedHours: 10,
      },
      {
        courseId: "Z1XEYB-eEeulXwp2iaqDJw",
        slug: "health-it-fundamentals",
        name: "Health Information Technology Fundamentals",
        partner: "Johns Hopkins University",
        estimatedHours: 10,
      },
      {
        courseId: "1-6HgCIEEey-7g6YTy-Atw",
        slug: "telehealth",
        name: "Foundations of Telehealth",
        partner: "Johns Hopkins University",
        estimatedHours: 10,
      },
      {
        courseId: "CUOh2pFrEe-KjBKlSS1PLQ",
        slug: "medical-administrative-assistants-and-office-procedures",
        name: "Medical Administrative Assistants and Office Procedures",
        partner: "MedCerts",
        estimatedHours: 10,
      },
      {
        courseId: "uDMpp-fMEe-mrRK-FPQYAw",
        slug: "introduction-to-certified-professional-biller",
        name: "Introduction to Certified Professional Biller",
        partner: "AAPC",
        estimatedHours: 10,
      },
    ],
  },
  "ai-professional-developer-certificate-ibm": {
    workforceProgramSlug: "ai-professional-developer-certificate-ibm",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "0TmQl",
    courseraCollectionTitle: "AI Practitioner Professional Certificate",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 16,
    courses: [
      {
        courseId: "mR7MlUaTEemuHQ4HpHozrA",
        slug: "introduction-to-ai",
        name: "Introduction to Artificial Intelligence (AI)",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "h5dcezicEeyZlQoNyXy15Q",
        slug: "artificial-intelligence-an-overview",
        name: "Artificial Intelligence: An Overview",
        partner: "Politecnico di Milano",
        estimatedHours: 10,
      },
      {
        courseId: "GCTyHE2LEeyLIRLL9niz0w",
        slug: "introduction-to-digital-transformation-part-1",
        name: "Introduction to Digital Transformation Part 1",
        partner: "University of Virginia Darden School Foundation",
        estimatedHours: 10,
      },
      {
        courseId: "hVwck3epEfC1jRJm2R_Okw",
        slug: "ai-foundations-for-all",
        name: "AI For All",
        partner: "AI CERTs",
        estimatedHours: 10,
      },
      {
        courseId: "954g6F1WEe6iARI3FlRl8w",
        slug: "ai-strategy",
        name: "AI Concepts and Strategy",
        partner: "Rutgers the State University of New Jersey",
        estimatedHours: 10,
      },
      {
        courseId: "z-d7VBReEe-r_Ar_6dbL9Q",
        slug: "ai-for-professional-communication",
        name: "AI for Professional Communication",
        partner: "Kennesaw State University",
        estimatedHours: 10,
      },
      {
        courseId: "SOTCddsLEfC1UxIkq1JqIw",
        slug: "understand-apply-artificial-intelligence-fundamentals",
        name: "Understand and Apply Artificial Intelligence Fundamentals",
        partner: "EDUCBA",
        estimatedHours: 10,
      },
      {
        courseId: "CQXkoGIKEe6yuQ41HILERQ",
        slug: "ai-for-business-generation-and-prediction",
        name: "AI for Business: Generation & Prediction",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "YUfX_FFcEemHkRLmf0JQJA",
        slug: "ai-ethics",
        name: "Artificial Intelligence: Ethics & Societal Challenges",
        partner: "Lund University",
        estimatedHours: 10,
      },
      {
        courseId: "w1jkc9spEfCQRRIzUgLPlQ",
        slug: "packt-chatgpt-foundations-amzvj",
        name: "ChatGPT - Foundations",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "SaiktYS1Ee66wg5jL1EOqw",
        slug: "chatgpt-for-beginners-market-research-ai",
        name: "ChatGPT for Beginners: Using AI for Market Research",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "ZruIud55Ee-L_Q47HwVgtw",
        slug: "ai-for-everyone-ai-fundamentals-with-claude",
        name: "AI Fundamentals with Claude",
        partner: "Advancing Women in Tech, Anthropic",
        estimatedHours: 10,
      },
      {
        courseId: "oc80ZNm-EfCZihIC4LWgUw",
        slug: "sales-with-ai",
        name: "Sales with AI",
        partner: "AI CERTs",
        estimatedHours: 10,
      },
      {
        courseId: "tQhqTtzuEfC6bA4wlNz8zQ",
        slug: "ai-for-marketing",
        name: "AI for Marketing",
        partner: "AI CERTs",
        estimatedHours: 10,
      },
      {
        courseId: "Ci-CgAWfEfCd-gr_6GMchQ",
        slug: "packt-salesforce-certified-ai-associate-certification-a3r1f",
        name: "Salesforce Certified AI Associate Certification",
        partner: "Packt",
        estimatedHours: 10,
      },
      {
        courseId: "MvVSdbBHEfCsnQ73ldDVQw",
        slug: "aws-artificial-intelligence-practitioner",
        name: "AWS Artificial Intelligence Practitioner",
        partner: "Amazon Web Services",
        estimatedHours: 10,
      },
    ],
  },
  "data-science-professional-certificate-ibm": {
    workforceProgramSlug: "data-science-professional-certificate-ibm",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "pWA8u",
    courseraCollectionTitle: "Data Science Professional Certificate (IBM)",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 12,
    courses: [
      {
        courseId: "r0GnHOZaEees-Q6jQMxlrg",
        slug: "what-is-datascience",
        name: "What is Data Science?",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "oCBU5_VYEeeBQA7SG0nILA",
        slug: "open-source-tools-for-data-science",
        name: "Tools for Data Science",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "OFt7o_8IEee1YxLCJ0cSDA",
        slug: "data-science-methodology",
        name: "Data Science Methodology",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "ejOz7RDUEei99hK0xs-tsg",
        slug: "python-for-applied-data-science-ai",
        name: "Python for Data Science, AI & Development",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "aOsrKiujEe6mDAo3fVlzHw",
        slug: "python-data-science",
        name: "Python for Data Science",
        partner: "Fractal Analytics",
        estimatedHours: 10,
      },
      {
        courseId: "GDQMSxDWEeitFhJL4G-A_g",
        slug: "sql-data-science",
        name: "Databases and SQL for Data Science with Python",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "fYuElDEgEeiCvhLLCIZW_A",
        slug: "data-analysis-with-python",
        name: "Data Analysis with Python",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "ORAIlTLtEeizIBKbQHnlqg",
        slug: "python-for-data-visualization",
        name: "Data Visualization with Python",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "8UjeMk-mEeit4g4GsxE4dg",
        slug: "machine-learning-with-python",
        name: "Machine Learning with Python",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "uZZCOk-0Eei5shJ0GHcv-g",
        slug: "applied-data-science-capstone",
        name: "Applied Data Science Capstone",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "hIyjm5CKEe63Ww6tPe9iow",
        slug: "generative-ai-elevate-your-data-science-career",
        name: "Generative AI: Elevate Your Data Science Career",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "tI6I6GHOEeyipgpI5l_HwQ",
        slug: "career-guide-and-interview-prep-for-data-science-pc",
        name: "Data Scientist Career Guide and Interview Preparation",
        partner: "IBM",
        estimatedHours: 10,
      },
    ],
  },
  "digital-marketing-e-commerce-google": {
    workforceProgramSlug: "digital-marketing-e-commerce-google",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "pzskj",
    courseraCollectionTitle: "Digital Marketing & E-Commerce Professional Certificate",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 11,
    courses: [
      {
        courseId: "g-0dF3JpEeys9RJMWW48Yw",
        slug: "foundations-of-digital-marketing-and-e-commerce",
        name: "Foundations of Digital Marketing and E-commerce",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "dG13cHJKEeys9RJMWW48Yw",
        slug: "attract-and-engage-customers",
        name: "Attract and Engage Customers with Digital Marketing",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "HjlVBHJLEeys9RJMWW48Yw",
        slug: "from-likes-to-leads",
        name: "From Likes to Leads: Interact with Customers Online",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "MBqC4XJLEeys9RJMWW48Yw",
        slug: "think-outside-the-inbox",
        name: "Think Outside the Inbox: Email Marketing",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "FOu5AXsIEeynSxJpnIcphQ",
        slug: "assess-for-success",
        name: "Assess for Success: Marketing Analytics and Measurement",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "uRHCCWFiEeuu-xLe1JcYrQ",
        slug: "social-media-digital-marketing-fundamentals",
        name: "Social Media and Digital Marketing Fundamentals",
        partner: "Digital Marketing Institute",
        estimatedHours: 10,
      },
      {
        courseId: "0FyJ84IeEe-uPQ6cY8b-gw",
        slug: "social-media-content-and-strategy",
        name: "Social Media Content and Strategy",
        partner: "Adobe",
        estimatedHours: 10,
      },
      {
        courseId: "SsanZuvgEfCEtA75x5Rx3w",
        slug: "digital-marketing-channels",
        name: "Strategic Digital Marketing: Digital Marketing Channels",
        partner: "University of Arizona",
        estimatedHours: 10,
      },
      {
        courseId: "UK7yonsIEey1tgpUmO8AYQ",
        slug: "satisfaction-guaranteed",
        name: "Satisfaction Guaranteed: Develop Customer Loyalty Online",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "gtaaAQWpEfGgHhL0Iuu-6Q",
        slug: "seo-and-content-optimization-for-digital-marketing",
        name: "SEO and Content Optimization for Digital Marketing",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "RekNoB1LEfGuBw5BLqxbOQ",
        slug: "digital-marketing-with-genai",
        name: "Digital Marketing with AI",
        partner: "SkillsBooster Academy",
        estimatedHours: 10,
      },
    ],
  },
  "data-analytics-professional-certificate-google": {
    workforceProgramSlug: "data-analytics-professional-certificate-google",
    courseraProgramId: "TpIlAogTQ8-SJQKIE8PP9w",
    courseraProgramName: "Workforce Advancement Project",
    courseraCollectionId: "Qa9KU",
    courseraCollectionTitle: "Data Analytics Professional Certificate (Google)",
    publicProgramUrl: "https://www.coursera.org/programs/workforce-advancement-project-8a3f0",
    courseCount: 13,
    courses: [
      {
        courseId: "ZWYBq9zVEeqMbw6VbjEnNw",
        slug: "introduction-to-data-analytics",
        name: "Introduction to Data Analytics",
        partner: "IBM",
        estimatedHours: 10,
      },
      {
        courseId: "kvb6uMbTEeqZOA5eKDHL-w",
        slug: "foundations-data",
        name: "Foundations: Data, Data, Everywhere",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "ZEB-Lgp9Eeun_RJEc0KNDw",
        slug: "ask-questions-make-decisions",
        name: "Ask Questions to Make Data-Driven Decisions",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "bN9fcgp9Eeu0VAqNda9Xjw",
        slug: "data-preparation",
        name: "Prepare Data for Exploration",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "MYbEugyHEfGWGg5tlkdcvw",
        slug: "retrieve--prep-data",
        name: "Retrieve & Prep Data",
        partner: "Coursera",
        estimatedHours: 10,
      },
      {
        courseId: "c9dt2Qp9Eeuf7w5EwYPThw",
        slug: "process-data",
        name: "Process Data from Dirty to Clean",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "gawUVgp9EeuyHQ758rw-Yw",
        slug: "analyze-data",
        name: "Analyze Data to Answer Questions",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "iLNlSQp9Eeun_RJEc0KNDw",
        slug: "visualize-data",
        name: "Share Data Through the Art of Visualization",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "joRZVwp9Eeun_RJEc0KNDw",
        slug: "data-analysis-r",
        name: "Data Analysis with R Programming",
        partner: "Google",
        estimatedHours: 10,
      },
      {
        courseId: "r8RBMXEzEe-uqRL6e5om0w",
        slug: "data-privacy-security-governance-risk-and-compliance",
        name: "Data Privacy, Security, Governance, Risk and Compliance",
        partner: "SkillUp",
        estimatedHours: 10,
      },
      {
        courseId: "OUTGOrvTEeWuCAqiwoZfSw",
        slug: "excel-data-analysis",
        name: "Introduction to Data Analysis Using Excel",
        partner: "Rice University",
        estimatedHours: 10,
      },
      {
        courseId: "aqZafM_BEfCL0wr__9J4Qw",
        slug: "power-bi-data-analysis-reporting-connecting-lo095214",
        name: "Power BI: Data Analysis, Reporting, and Connecting",
        partner: "Logical Operations",
        estimatedHours: 10,
      },
      {
        courseId: "m0fACXB0EeulIxJCZb_vVQ",
        slug: "google-data-analytics-capstone",
        name: "Google Data Analytics Capstone: Complete a Case Study",
        partner: "Google",
        estimatedHours: 10,
      },
    ],
  },
};

export const DISCOVERED_COURSERA_COURSE_SLUG_MAP: Record<string, string[]> = Object.fromEntries(
  Object.entries(DISCOVERED_COURSERA_PROGRAMS).map(([programSlug, mapping]) => [
    programSlug,
    mapping.courses.map((course) => course.slug),
  ])
) as Record<string, string[]>;

export const DISCOVERED_COURSERA_COLLECTION_IDS: Record<string, string> = Object.fromEntries(
  Object.entries(DISCOVERED_COURSERA_PROGRAMS).map(([programSlug, mapping]) => [
    programSlug,
    mapping.courseraCollectionId,
  ])
) as Record<string, string>;
