import { NextRequest, NextResponse } from 'next/server';
import { getUser } from '@/lib/auth/server';
import { isAdmin } from '@/lib/auth/roles';
import { prisma } from '@/lib/db/prisma';
import { getProgramBySlug } from '@/lib/content/programs';
import { buildCsv, csvDate } from '@/lib/csv';
import { MEMBER_ONLY_WHERE } from '@/lib/admin/memberOnlyWhere';

/**
 * GET /api/admin/cohort-export?program=<slug>
 *
 * Cohort CSV for grant reporting (e.g. WIOA). Lists every member in a given program
 * with placement + wage data, course progress, assessment outcome, employment status
 * at enroll, and self-reported employment barriers from the pre-screening response.
 *
 * Admin-only. Streams text/csv as an attachment.
 */
export async function GET(req: NextRequest) {
  const user = await getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  if (!(await isAdmin(user.id)))
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

  const slug = req.nextUrl.searchParams.get('program')?.trim() ?? '';
  if (!slug) {
    return NextResponse.json(
      { error: 'Missing required `program` query parameter (program slug).' },
      { status: 400 },
    );
  }

  const program = getProgramBySlug(slug);
  if (!program) {
    return NextResponse.json(
      { error: `Unknown program slug: ${slug}` },
      { status: 404 },
    );
  }

  try {
  const EXPORT_LIMIT = 10_000;
  const users = await prisma.user.findMany({
    where: {
      deletedAt: null,
      enrolledProgram: slug,
      ...MEMBER_ONLY_WHERE,
    },
    orderBy: { createdAt: 'desc' },
    take: EXPORT_LIMIT,
    select: {
      id: true,
      fullName: true,
      email: true,
      enrolledAt: true,
      coursesCompleted: true,
      assessmentCompleted: true,
      assessmentScorePct: true,
      profile: {
        select: {
          employmentStatus: true,
        },
      },
      preScreeningResponse: {
        select: {
          employmentStatus: true,
          barrier: true,
        },
      },
      placementRecord: {
        select: {
          employerName: true,
          jobTitle: true,
          startDate: true,
          salaryOffered: true,
          wageAtFollowUp: true,
          retentionStatus: true,
          placedAt: true,
        },
      },
    },
  });

  const totalCourses = program.courses.length;

  const csvColumns = [
    'Member Name',
    'Email',
    'Enrollment Date',
    'Program Slug',
    'Courses Completed',
    'Total Courses',
    'Completion %',
    'Assessment Completed',
    'Assessment Score',
    'Employer',
    'Job Title',
    'Start Date',
    'Annual Salary',
    'Hourly Wage (est.)',
    'Wage at Follow-Up',
    'Retention Status',
    'Employment Status at Enroll',
    'Employment Barriers',
  ];

  const csvRows = users.map((u) => {
    const completed = Array.isArray(u.coursesCompleted)
      ? (u.coursesCompleted as string[])
      : [];
    const completionPct =
      totalCourses > 0 ? Math.round((completed.length / totalCourses) * 100) : 0;

    const p = u.placementRecord;
    // Hourly wage estimate from annual salary (40h/wk × 52wk = 2080h)
    const hourly =
      p?.salaryOffered != null
        ? `$${(p.salaryOffered / 2080).toFixed(2)}`
        : '';
    const annual =
      p?.salaryOffered != null
        ? `$${p.salaryOffered.toLocaleString()}`
        : '';
    const followUp =
      p?.wageAtFollowUp != null
        ? `$${p.wageAtFollowUp.toLocaleString()}`
        : '';

    // Prefer pre-screening employment status (captured at enroll); fall back to profile.
    const employmentAtEnroll =
      u.preScreeningResponse?.employmentStatus ??
      u.profile?.employmentStatus ??
      '';

    const barriers = u.preScreeningResponse?.barrier ?? '';

    return [
      u.fullName,
      u.email,
      csvDate(u.enrolledAt),
      slug,
      completed.length,
      totalCourses,
      totalCourses > 0 ? `${completionPct}%` : '',
      u.assessmentCompleted ? 'Yes' : 'No',
      u.assessmentScorePct != null ? `${u.assessmentScorePct}%` : '',
      p?.employerName ?? '',
      p?.jobTitle ?? '',
      csvDate(p?.startDate ?? p?.placedAt),
      annual,
      hourly,
      followUp,
      p?.retentionStatus ?? '',
      employmentAtEnroll,
      barriers,
    ];
  });

  const csv = buildCsv(csvColumns, csvRows, {
    reportTitle: `Cohort Export — ${program.title}`,
    notes:
      'Placement + wage cohort export for grant reporting (e.g. WIOA). Generated by WorkforceAP.',
  });

  const date = new Date().toISOString().slice(0, 10);
  const filename = `cohort-${slug}-${date}.csv`;

  const headers: Record<string, string> = {
    'Content-Type': 'text/csv; charset=utf-8',
    'Content-Disposition': `attachment; filename="${filename}"`,
    'Cache-Control': 'no-store',
  };
  if (users.length >= EXPORT_LIMIT) {
    headers['X-Export-Truncated'] = 'true';
    headers['X-Export-Limit'] = `${EXPORT_LIMIT}`;
  }

  return new NextResponse(csv, { status: 200, headers });
  } catch {
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}
