#!/usr/bin/env bash
# Subset Material Symbols Outlined from scripts/material-symbol-glyphs.txt (generated by extract-material-symbol-glyphs.mjs).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENV="$ROOT/.venv-fonttools"
if [[ ! -x "$VENV/bin/python" ]]; then
  python3 -m venv "$VENV"
fi
"$VENV/bin/pip" install -q fonttools brotli
node "$ROOT/scripts/extract-material-symbol-glyphs.mjs"
"$VENV/bin/python" "$ROOT/scripts/subset-material-symbols.py"
