import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { getUser } from '@/lib/auth/server';

/**
 * POST /api/ai/export-pdf
 * Body: { text: string, title?: string, toolName?: string }
 * Returns: PDF file download
 */
export async function POST(req: NextRequest) {
  const user = await getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await req.json();
  const { text, title, toolName } = body as { text?: string; title?: string; toolName?: string };

  if (!text || typeof text !== 'string') {
    return NextResponse.json({ error: 'text is required' }, { status: 400 });
  }

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 612; // US Letter
  const pageHeight = 792;
  const margin = 50;
  const maxWidth = pageWidth - margin * 2;
  const fontSize = 10;
  const lineHeight = fontSize * 1.4;
  const titleSize = 16;

  // Wrap text into lines
  const wrapText = (txt: string, f: typeof font, size: number, max: number): string[] => {
    const lines: string[] = [];
    for (const paragraph of txt.split('\n')) {
      if (paragraph.trim() === '') {
        lines.push('');
        continue;
      }
      const words = paragraph.split(' ');
      let currentLine = '';
      for (const word of words) {
        const testLine = currentLine ? `${currentLine} ${word}` : word;
        const width = f.widthOfTextAtSize(testLine, size);
        if (width > max && currentLine) {
          lines.push(currentLine);
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }
      if (currentLine) lines.push(currentLine);
    }
    return lines;
  };

  const lines = wrapText(text, font, fontSize, maxWidth);

  // Paginate
  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  // Title
  if (title) {
    page.drawText(title, { x: margin, y, font: boldFont, size: titleSize, color: rgb(0.1, 0.1, 0.1) });
    y -= titleSize * 1.6;
  }

  // Subtitle
  const subtitle = toolName ? `Generated by WorkforceAP ${toolName}` : 'Generated by WorkforceAP';
  page.drawText(subtitle, { x: margin, y, font, size: 8, color: rgb(0.5, 0.5, 0.5) });
  y -= 24;

  // Body
  for (const line of lines) {
    if (y < margin + lineHeight) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
    if (line.trim()) {
      page.drawText(line, { x: margin, y, font, size: fontSize, color: rgb(0.15, 0.15, 0.15) });
    }
    y -= lineHeight;
  }

  const pdfBytes = await pdfDoc.save();
  const pdfBuffer = Buffer.from(pdfBytes);

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${(title || 'workforceap-export').replace(/[^a-zA-Z0-9-_ ]/g, '')}.pdf"`,
    },
  });
}
