import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, PDFFont, rgb, StandardFonts } from 'pdf-lib';
import { getUser } from '@/lib/auth/server';

/** Map common Unicode from AI output to WinAnsi-safe equivalents for StandardFonts. */
function sanitizeForWinAnsi(text: string): string {
  return text
    .replace(/\u00A0/g, ' ')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")
    .replace(/[\u201C\u201D\u201E\u201F]/g, '"')
    .replace(/[\u2022\u2023\u2043\u2219\u00B7]/g, '*')
    .replace(/\u2026/g, '...')
    .replace(/\u2192/g, '->')
    .replace(/\u2190/g, '<-')
    .replace(/[^\n\r\t\x20-\x7E\xA0-\xFF]/g, '?');
}

function wrapParagraphWords(txt: string, f: PDFFont, size: number, max: number): string[] {
  const lines: string[] = [];
  if (txt.trim() === '') return [''];
  const words = txt.split(' ');
  let currentLine = '';
  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const width = f.widthOfTextAtSize(testLine, size);
    if (width > max && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines;
}

/**
 * POST /api/ai/export-pdf
 * Body: { text: string, title?: string, toolName?: string }
 * Returns: PDF file download with WorkforceAP branding header
 */
export async function POST(req: NextRequest) {
  try {
    const user = await getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const { text, title, toolName } = body as { text?: string; title?: string; toolName?: string };

    if (!text || typeof text !== 'string') {
      return NextResponse.json({ error: 'text is required' }, { status: 400 });
    }

    const rawText = sanitizeForWinAnsi(text);
    const safeTitle = title ? sanitizeForWinAnsi(title) : undefined;

    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const pageWidth = 612; // US Letter
    const pageHeight = 792;
    const margin = 50;
    const maxWidth = pageWidth - margin * 2;
    const fontSize = 10;
    const headingSize = 11;
    const lineHeight = fontSize * 1.5;

    type BodyLine = { kind: 'heading'; text: string } | { kind: 'body'; text: string };
    const bodyLines: BodyLine[] = [];

    for (const paragraph of rawText.split('\n')) {
      if (paragraph.trim() === '') {
        bodyLines.push({ kind: 'body', text: '' });
        continue;
      }
      const isHeading = /^#{1,3}\s/.test(paragraph);
      const cleanMarkdown = paragraph.replace(/\*\*/g, '');
      if (isHeading) {
        const rest = cleanMarkdown.replace(/^#{1,3}\s+/, '');
        for (const w of wrapParagraphWords(rest, boldFont, headingSize, maxWidth)) {
          bodyLines.push({ kind: 'heading', text: w });
        }
      } else {
        for (const w of wrapParagraphWords(cleanMarkdown, font, fontSize, maxWidth)) {
          bodyLines.push({ kind: 'body', text: w });
        }
      }
    }

    // ── First page ──
    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;

    // ── Branding header bar ──
    // Accent color bar at top
    const accentR = 173 / 255;
    const accentG = 44 / 255;
    const accentB = 77 / 255;
    page.drawRectangle({ x: 0, y: pageHeight - 48, width: pageWidth, height: 48, color: rgb(accentR, accentG, accentB) });

    // Brand name in header
    page.drawText('Workforce Advancement Project', {
      x: margin,
      y: pageHeight - 32,
      font: boldFont,
      size: 13,
      color: rgb(1, 1, 1),
    });
    page.drawText('workforceap.org', {
      x: pageWidth - margin - font.widthOfTextAtSize('workforceap.org', 9),
      y: pageHeight - 32,
      font,
      size: 9,
      color: rgb(1, 0.9, 0.9),
    });

    y = pageHeight - 48 - 20;

    // ── Document title ──
    if (safeTitle) {
      page.drawText(safeTitle, {
        x: margin,
        y,
        font: boldFont,
        size: 16,
        color: rgb(accentR, accentG, accentB),
      });
      y -= 24;
    }

    // ── Tool / generation meta ──
    const genDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const metaLine = sanitizeForWinAnsi(
      toolName
        ? `Generated by WorkforceAP ${toolName} · ${genDate}`
        : `Generated by Workforce Advancement Project · ${genDate}`,
    );
    page.drawText(metaLine, { x: margin, y, font, size: 8, color: rgb(0.5, 0.5, 0.5) });
    y -= 20;

    // Separator rule
    page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
    y -= 16;

    // ── Body text ──
    for (const line of bodyLines) {
      const lh = line.kind === 'heading' ? headingSize * 1.5 : lineHeight;
      if (y < margin + lh) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        // Minimal header on continuation pages
        page.drawRectangle({ x: 0, y: pageHeight - 24, width: pageWidth, height: 24, color: rgb(accentR, accentG, accentB) });
        page.drawText('Workforce Advancement Project', { x: margin, y: pageHeight - 17, font, size: 8, color: rgb(1, 1, 1) });
        y = pageHeight - 24 - 20;
      }
      if (line.text.trim()) {
        if (line.kind === 'heading') {
          y -= 4;
          page.drawText(line.text, { x: margin, y, font: boldFont, size: headingSize, color: rgb(accentR, accentG, accentB) });
          y -= lh + 2;
        } else {
          page.drawText(line.text, { x: margin, y, font, size: fontSize, color: rgb(0.15, 0.15, 0.15) });
          y -= lh;
        }
      } else {
        y -= lineHeight * 0.6;
      }
    }

    // ── Footer on all pages ──
    const pageCount = pdfDoc.getPageCount();
    for (let i = 0; i < pageCount; i++) {
      const pg = pdfDoc.getPage(i);
      const footerText = `Workforce Advancement Project · workforceap.org · Page ${i + 1} of ${pageCount}`;
      pg.drawLine({ start: { x: margin, y: margin - 4 }, end: { x: pageWidth - margin, y: margin - 4 }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
      pg.drawText(footerText, { x: margin, y: margin - 18, font, size: 8, color: rgb(0.55, 0.55, 0.55) });
    }

    const pdfBytes = await pdfDoc.save();
    const pdfBuffer = Buffer.from(pdfBytes);
    const filenameBase = (safeTitle ?? 'workforceap-export').replace(/[^a-zA-Z0-9-_ ]/g, '').slice(0, 60).trim() || 'workforceap-export';

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filenameBase}.pdf"`,
      },
    });
  } catch (error) {
    console.error('[ai/export-pdf] error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
