import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { getUser } from '@/lib/auth/server';

/**
 * POST /api/ai/export-pdf
 * Body: { text: string, title?: string, toolName?: string }
 * Returns: PDF file download with WorkforceAP branding header
 */
export async function POST(req: NextRequest) {
  try {
    const user = await getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const { text, title, toolName } = body as { text?: string; title?: string; toolName?: string };

    if (!text || typeof text !== 'string') {
      return NextResponse.json({ error: 'text is required' }, { status: 400 });
    }

    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const pageWidth = 612; // US Letter
    const pageHeight = 792;
    const margin = 50;
    const maxWidth = pageWidth - margin * 2;
    const fontSize = 10;
    const lineHeight = fontSize * 1.5;

    // Wrap text into lines
    const wrapText = (txt: string, f: typeof font, size: number, max: number): string[] => {
      const lines: string[] = [];
      for (const paragraph of txt.split('\n')) {
        if (paragraph.trim() === '') {
          lines.push('');
          continue;
        }
        const words = paragraph.split(' ');
        let currentLine = '';
        for (const word of words) {
          const testLine = currentLine ? `${currentLine} ${word}` : word;
          const width = f.widthOfTextAtSize(testLine, size);
          if (width > max && currentLine) {
            lines.push(currentLine);
            currentLine = word;
          } else {
            currentLine = testLine;
          }
        }
        if (currentLine) lines.push(currentLine);
      }
      return lines;
    };

    const bodyLines = wrapText(text, font, fontSize, maxWidth);

    // ── First page ──
    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;

    // ── Branding header bar ──
    // Accent color bar at top
    const accentR = 173 / 255;
    const accentG = 44 / 255;
    const accentB = 77 / 255;
    page.drawRectangle({ x: 0, y: pageHeight - 48, width: pageWidth, height: 48, color: rgb(accentR, accentG, accentB) });

    // Brand name in header
    page.drawText('Workforce Advancement Project', {
      x: margin,
      y: pageHeight - 32,
      font: boldFont,
      size: 13,
      color: rgb(1, 1, 1),
    });
    page.drawText('workforceap.org', {
      x: pageWidth - margin - boldFont.widthOfTextAtSize('workforceap.org', 9),
      y: pageHeight - 32,
      font,
      size: 9,
      color: rgb(1, 0.9, 0.9),
    });

    y = pageHeight - 48 - 20;

    // ── Document title ──
    if (title) {
      page.drawText(title, {
        x: margin,
        y,
        font: boldFont,
        size: 16,
        color: rgb(accentR, accentG, accentB),
      });
      y -= 24;
    }

    // ── Tool / generation meta ──
    const genDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const metaLine = toolName
      ? `Generated by WorkforceAP ${toolName} · ${genDate}`
      : `Generated by Workforce Advancement Project · ${genDate}`;
    page.drawText(metaLine, { x: margin, y, font, size: 8, color: rgb(0.5, 0.5, 0.5) });
    y -= 20;

    // Separator rule
    page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
    y -= 16;

    // ── Body text ──
    for (const line of bodyLines) {
      if (y < margin + lineHeight) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        // Minimal header on continuation pages
        page.drawRectangle({ x: 0, y: pageHeight - 24, width: pageWidth, height: 24, color: rgb(accentR, accentG, accentB) });
        page.drawText('Workforce Advancement Project', { x: margin, y: pageHeight - 17, font, size: 8, color: rgb(1, 1, 1) });
        y = pageHeight - 24 - 20;
      }
      if (line.trim()) {
        // Detect section headings (### or ## prefix)
        const isHeading = /^#{1,3}\s/.test(line);
        const cleanLine = line.replace(/^#{1,3}\s+/, '').replace(/\*\*/g, '');
        if (isHeading) {
          y -= 4;
          page.drawText(cleanLine, { x: margin, y, font: boldFont, size: 11, color: rgb(accentR, accentG, accentB) });
          y -= lineHeight + 2;
        } else {
          page.drawText(cleanLine, { x: margin, y, font, size: fontSize, color: rgb(0.15, 0.15, 0.15) });
          y -= lineHeight;
        }
      } else {
        y -= lineHeight * 0.6;
      }
    }

    // ── Footer on all pages ──
    const pageCount = pdfDoc.getPageCount();
    for (let i = 0; i < pageCount; i++) {
      const pg = pdfDoc.getPage(i);
      const footerText = `Workforce Advancement Project · workforceap.org · Page ${i + 1} of ${pageCount}`;
      pg.drawLine({ start: { x: margin, y: margin - 4 }, end: { x: pageWidth - margin, y: margin - 4 }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
      pg.drawText(footerText, { x: margin, y: margin - 18, font, size: 8, color: rgb(0.55, 0.55, 0.55) });
    }

    const pdfBytes = await pdfDoc.save();
    const pdfBuffer = Buffer.from(pdfBytes);
    const safeTitle = (title ?? 'workforceap-export').replace(/[^a-zA-Z0-9-_ ]/g, '').slice(0, 60).trim() || 'workforceap-export';

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${safeTitle}.pdf"`,
      },
    });
  } catch (error) {
    console.error('[ai/export-pdf] error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
