/**
 * Partner enrollment page loader (Phase B3).
 *
 * Resolves everything `/enroll/[partnerSlug]` needs from the database:
 * the partner row, its curated program catalog (hydrated against the
 * canonical `PROGRAMS` data so cards can never drift from the detail
 * pages), and — only when it is genuinely in force — the sponsorship
 * banner copy.
 *
 * Adding a school is data entry: a `Partner` row with
 * `enrollmentPageEnabled = true` plus `PartnerProgramCatalog` rows. No code.
 *
 * Deliberately contains no React (no JSX, no `server-only`, no `next/*`) so
 * it is directly unit-testable and the page stays a thin renderer over it.
 * The Prisma client is injectable (`deps.db`) for the same reason — the tests
 * never touch a database.
 */

import { formatFundingSourceLabel, getProgramBySlug } from '@/lib/content/programs';
import { prisma } from '@/lib/db/prisma';
import { logger } from '@/lib/observability/logger';
import {
  buildSponsoredSeatWhere,
  buildSponsorshipMessage,
  isSeatCapReached,
  isSponsorshipActive,
  type SponsoredSeatWhere,
  type SponsorshipPartner,
} from '@/lib/partners/sponsorship';

/**
 * Fallback catalog for a partner-school page whose `programCatalog` is empty.
 *
 * These are the five tracks Concordia High School launched with (Phase A).
 * A school row created without catalog rows is a data-entry omission, not an
 * instruction to show nothing — and a blank page in front of students days
 * before a rollout is the worst possible failure. Falling back keeps the page
 * useful while an admin fills the catalog in.
 */
export const SCHOOL_DEFAULT_SLUGS: readonly string[] = [
  'it-support-professional-certificate-ibm',
  'cybersecurity-professional-certificate-google',
  'data-analytics-professional-certificate-google',
  'project-management-professional-certificate-microsoft',
  'ux-design-professional-certificate-google',
];

/** The `Partner` columns the enrollment page reads. */
export type EnrollmentPagePartner = SponsorshipPartner & {
  slug: string;
  referralCode: string;
  active: boolean;
  status: string;
  logoUrl: string | null;
  brandColor: string | null;
  schoolDistrict: string | null;
  enrollmentPageEnabled: boolean;
  enrollmentHeadline: string | null;
  enrollmentBlurb: string | null;
};

/** The `PartnerProgramCatalog` columns the enrollment page reads. */
export type EnrollmentCatalogRow = {
  programSlug: string;
  displayOrder: number;
  featured: boolean;
  note: string | null;
};

/** Partner row plus its ordered catalog, as loaded in one query. */
export type EnrollmentPartnerRecord = EnrollmentPagePartner & {
  programCatalog: EnrollmentCatalogRow[];
};

/**
 * The slice of the Prisma client this loader uses. Narrowing it to two calls
 * keeps the unit tests honest (a hand-written stub is a few lines) without
 * pretending to model Prisma's generics.
 */
export type EnrollmentPageDb = {
  partner: {
    findUnique(args: {
      where: { slug: string };
      include: {
        programCatalog: {
          orderBy: [{ displayOrder: 'asc' }, { programSlug: 'asc' }];
        };
      };
    }): Promise<EnrollmentPartnerRecord | null>;
  };
  courseEnrollment: {
    count(args: { where: SponsoredSeatWhere }): Promise<number>;
  };
};

/** One program card, fully hydrated from the canonical catalog. */
export type EnrollmentProgramCard = {
  slug: string;
  title: string;
  categoryLabel: string;
  categoryColor: string;
  duration: string;
  /** e.g. `$55K–$72K` — an early-career estimate, always shown with its disclaimer. */
  salaryRange: string;
  /** Up to three, for the card's skill tags. */
  skills: string[];
  /** Credential partner (IBM, Google, …). */
  partner: string;
  /** Program funding badge ("WIOA/Grant"), independent of any sponsorship. */
  fundingLabel: string;
  featured: boolean;
  note: string | null;
};

/** Public cost copy for the page, generated by the shared helper. */
export type EnrollmentSponsorship = {
  /** From `buildSponsorshipMessage()` — the single source of public cost copy. */
  message: string;
  termLabel: string | null;
  /** Remaining funded seats when a cap is configured; null when uncapped. */
  seatsRemaining: number | null;
};

/**
 * Discriminated result so the page never has to guess why it got nothing:
 *  - `not-found` → no such partner, or the partner has no enrollment page.
 *  - `paused`    → the page exists but the partner is inactive. Students hold
 *                  printed links, so this renders a calm 200, never a 404.
 *  - `ok`        → render the page.
 */
export type EnrollmentPageData =
  | { kind: 'not-found' }
  | { kind: 'paused'; partner: EnrollmentPagePartner }
  | {
      kind: 'ok';
      partner: EnrollmentPagePartner;
      cards: EnrollmentProgramCard[];
      sponsorship: EnrollmentSponsorship | null;
    };

export type EnrollmentPageDeps = {
  /** Injected in tests; defaults to the app's Prisma client. */
  db?: EnrollmentPageDb;
  /** Injected in tests; defaults to `new Date()`. */
  now?: Date;
};

/**
 * Normalizes `Program.salary` ("Starting salary: $55K-$72K") to the compact
 * range the cards show ("$55K–$72K"). Mirrors `salaryRangeDisplay()` in the
 * marketing data module so the dynamic page reads identically to the static
 * page it replaces.
 */
export function formatSalaryRange(salary: string): string {
  const match = salary.match(/\$(\d+)K\s*[-–]\s*\$(\d+)K/i);
  if (match) return `$${parseInt(match[1], 10)}K–$${parseInt(match[2], 10)}K`;
  return salary.replace(/^Starting salary:\s*/i, '').trim();
}

/**
 * Hydrates catalog slugs into cards, skipping (and logging) anything that is
 * not in the canonical program list. A typo in one admin-entered catalog row
 * must cost that one card, not the whole page.
 */
function buildCards(
  partnerSlug: string,
  rows: readonly { programSlug: string; featured: boolean; note: string | null }[]
): EnrollmentProgramCard[] {
  const cards: EnrollmentProgramCard[] = [];
  for (const row of rows) {
    const program = getProgramBySlug(row.programSlug);
    if (!program) {
      logger.warn('enrollmentPage: catalog row references an unknown program slug', {
        partnerSlug,
        programSlug: row.programSlug,
      });
      continue;
    }
    cards.push({
      slug: program.slug,
      title: program.title,
      categoryLabel: program.categoryLabel,
      categoryColor: program.categoryColor,
      duration: program.duration,
      salaryRange: formatSalaryRange(program.salary),
      skills: program.skills.slice(0, 3),
      partner: program.partner,
      fundingLabel: formatFundingSourceLabel(program.fundingSource),
      featured: row.featured,
      note: row.note,
    });
  }
  return cards;
}

/**
 * Resolves the sponsorship banner, or null when there must not be one.
 *
 * Null in three cases, and the page shows neutral guidance rather than any
 * cost claim in all of them: the sponsorship is off, `now` is outside the
 * window, or the funded seats for this term are gone. The seat cap is a soft
 * cap at signup (the student still enrolls), but promising "no cost" on a
 * page whose funding is exhausted is a promise we can't keep.
 */
async function resolveSponsorship(
  partner: EnrollmentPagePartner,
  db: EnrollmentPageDb,
  now: Date
): Promise<EnrollmentSponsorship | null> {
  if (!isSponsorshipActive(partner, now)) return null;

  let seatsRemaining: number | null = null;
  const cap = partner.sponsorshipSeatCap;
  if (cap !== null && cap !== undefined) {
    const usedSeats = await db.courseEnrollment.count({
      where: buildSponsoredSeatWhere(partner),
    });
    if (isSeatCapReached(partner, usedSeats)) return null;
    seatsRemaining = Math.max(0, cap - usedSeats);
  }

  return {
    message: buildSponsorshipMessage(partner),
    termLabel: partner.sponsorshipTermLabel?.trim() || null,
    seatsRemaining,
  };
}

/**
 * Loads everything `/enroll/<slug>` renders. The URL segment IS the partner
 * slug (see `lib/partners/chsPartner.ts`), so this is a direct lookup.
 */
export async function getEnrollmentPageData(
  slug: string,
  deps: EnrollmentPageDeps = {}
): Promise<EnrollmentPageData> {
  // One documented cast at the injection point: Prisma's generated client is
  // structurally compatible with (and much wider than) `EnrollmentPageDb`,
  // but its overloaded generic signatures don't assign cleanly to a
  // hand-written seam.
  const db = deps.db ?? (prisma as unknown as EnrollmentPageDb);
  const now = deps.now ?? new Date();

  const partner = await db.partner.findUnique({
    where: { slug },
    include: {
      programCatalog: { orderBy: [{ displayOrder: 'asc' }, { programSlug: 'asc' }] },
    },
  });

  // No partner, or the partner has no enrollment page: genuinely nothing here.
  if (!partner || partner.enrollmentPageEnabled === false) return { kind: 'not-found' };

  const { programCatalog, ...partnerFields } = partner;

  // The page is enabled but the partner is switched off. Students are holding
  // printed links — explain, don't 404.
  if (!partnerFields.active || partnerFields.status !== 'active') {
    return { kind: 'paused', partner: partnerFields };
  }

  const rows =
    programCatalog.length > 0
      ? programCatalog
      : SCHOOL_DEFAULT_SLUGS.map((programSlug) => ({
          programSlug,
          featured: false,
          note: null,
        }));

  const cards = buildCards(partnerFields.slug, rows);
  const sponsorship = await resolveSponsorship(partnerFields, db, now);

  return { kind: 'ok', partner: partnerFields, cards, sponsorship };
}
